# Generated by Django 4.2.15 on 2024-12-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldata',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
